version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: omni-gym-db
    environment:
      POSTGRES_DB: omni_gym
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d omni_gym"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./omni-gym-api
      dockerfile: Dockerfile
    container_name: omni-gym-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/omni_gym
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - api-uploads:/app/uploads

volumes:
  pgdata:
  api-uploads:
