export { default as InterBlack } from './Inter-Black.otf';
export { default as InterBold } from './Inter-Bold.otf';
export { default as InterExtraBold } from './Inter-ExtraBold.otf';
export { default as InterExtraLight } from './Inter-ExtraLight.otf';
export { default as InterLight } from './Inter-Light.otf';
export { default as InterMedium } from './Inter-Medium.otf';
export { default as InterRegular } from './Inter-Regular.otf';
export { default as InterSemiBold } from './Inter-SemiBold.otf';
export { default as InterThin } from './Inter-Thin.otf';

export { default as MontserratBlack } from './Montserrat-Black.otf';
export { default as MontserratBold } from './Montserrat-Bold.otf';
export { default as MontserratExtraBold } from './Montserrat-ExtraBold.otf';
export { default as MontserratExtraLight } from './Montserrat-ExtraLight.otf';
export { default as MontserratLight } from './Montserrat-Light.otf';
export { default as MontserratMedium } from './Montserrat-Medium.otf';
export { default as MontserratRegular } from './Montserrat-Regular.otf';
export { default as MontserratSemiBold } from './Montserrat-SemiBold.otf';
export { default as MontserratThin } from './Montserrat-Thin.otf';
